package pers.ljy.background.model;


import java.io.Serializable;

/***
 * 用户信息
 * @author ljy
 *
 */
public class UserInfoEntity implements Serializable {
    /**
     * 
     */
    private Integer id;

    /**
     * 用户编号
     */
    private String userNumber;

    /**
     * 昵称
     */
    private String userNickname;

    /**
     * 邮箱
     */
    private String userEmail;

    /**
     * 电话
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     * @return id_
     */
    public Integer getId() {
        return id;
    }

    /**
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 用户编号
     * @return user_number_
     */
    public String getUserNumber() {
        return userNumber;
    }

    /**
     * 用户编号
     * @param userNumber
     */
    public void setUserNumber(String userNumber) {
        this.userNumber = userNumber == null ? null : userNumber.trim();
    }

    /**
     * 昵称
     * @return user_nickname_
     */
    public String getUserNickname() {
        return userNickname;
    }

    /**
     * 昵称
     * @param userNickname
     */
    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname == null ? null : userNickname.trim();
    }

    /**
     * 邮箱
     * @return user_email_
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * 邮箱
     * @param userEmail
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * 电话
     * @return user_phone_
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * 电话
     * @param userPhone
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }
}